trigger:
- master

variables:
  DisplayVersion: $[counter(variables['DisplayPrefix'], 1)]

stages:
- stage: format
  displayName: 'format'
  jobs:
  - job: format
    displayName: 'clang'
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: ./templates/format-check.yml
- stage: build
  dependsOn: format
  displayName: 'build'
  jobs:
  - job: build
    displayName: 'windows-msvc'
    pool:
      vmImage: vs2017-win2016
    steps:
    - template: ./templates/sync-source.yml
      parameters:
        artifactSource: $(parameters.artifactSource)
        needSubmodules: 'true'
    - template: ./templates/build-msvc.yml
      parameters:
        artifactSource: 'false'
        cache: $(parameters.cache)
        version: $(DisplayVersion)
