stages:
- stage: format
  displayName: 'format'
  jobs:
  - job: format
    displayName: 'clang'
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: ./templates/format-check.yml
      parameters:
        artifactSource: 'false'
- stage: build
  displayName: 'build'
  dependsOn: format
  jobs:
  - template: ./templates/build-standard.yml
  - template: ./templates/build-testing.yml